name:                io-string-like
version:             0.1.0.1
github:              "clintonmead/io-string-like"
license:             BSD3
author:              "Clinton Mead"
maintainer:          "clintonmead@gmail.com"
copyright:           "Copyright: (c) 2018 Clinton Mead"

synopsis:            Classes to handle Prelude style IO functions for different datatypes
category:            Data

description:
  The functions in the Prelude such as "getContents", "putStr" only work for plain Strings.


  There are similar functions in "ByteString" for reading and writing, as well as \"Text\".


  This requires one to import the appropriate functions, usually qualified, for the
  particular datatype one is using. Changing the datatype at the very least involves
  changing import statements across your program.


  The package introduces classes to overload functions like "getContents", "putStr"
  over multiple datatypes, so implementations can be changed easily.


  All the code documentation is in "System.IO.StringLike.Impl".


  All the other modules are just re-exports.
dependencies:
- base >= 4.7 && < 5
- binary

library:
  source-dirs: src
  dependencies:
  - bytestring
  - text
  ghc-options: -Wall
